### ISSUE TITLE
Military Installation Integration

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#1]
Need to merge this feature from our old mission

**Comment by SpanishSurfer** [comment]
8eba8fbae3260c6963f833d10439a3149e2f529e

**Comment by Liveandletdie** [comment]
Ill try to look into this soon

**Comment by Liveandletdie** [comment]
I got this almost good to go, everything is working fine but having trouble with the selling of bases, the structures sell fine and it limits you to 2 bases as it should......however it does not remove/update the  town links/base areas....any ideas?

**Comment by thecoolestname36** [comment]
Check if you can build a factory there once the military installation is gone, if not, I'm guessing its probably something to do with an FSM in strat_mode markers system.  Maybe this will point you in the right direction, I spent about 30 minutes diggiging real quick but dont have much time tonight: https://github.com/OFPSDEV/BECTI/blob/master/becti_zerty_SS.Altis/addons/strat_mode/FSM/town_markers.fsm

**Comment by Liveandletdie** [comment]
Thanks for the input, ill try to check it out later today. Either way ill think ill upload the mission files to git....ill keep you posted.

**Comment by Liveandletdie** [comment]
yea just tested it, it works just like it should, once you sell it and all factories/installation gone, it does not allow you to build but the circle remains.....ill keep hunting, i went ahead and uploaded the files so if anyone else is motivated or knows a solution can help!
