### ISSUE TITLE
Add MLRS to OPFOR

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#36]

**Comment by MagnetAss** [comment]
Got a very nice skin for it in this addon: https://forums.bistudio.com/topic/173597-aaf-vehicles-with-csat-camo/

**Comment by MagnetAss** [comment]
working on this now

**Comment by SpanishSurfer** [comment]
I'll take care of it. Your skins look great but to save room I'm going to
retexture the mlrs with the same method as the mhq and mohawk. It uses 0
extra space.

**Comment by MagnetAss** [comment]
aww but it looks so purty :) http://imgur.com/g7jKvlB

**Comment by MagnetAss** [comment]
Upped the size to 10mb however. :/

**Comment by MagnetAss** [comment]
Maybe next time we have an event I'll throw together a universal AAF pack for the req. downloads. The  Striders would be cool to use /w the new periscope.
