### ISSUE TITLE
Add clickable link to OFPS (wasteland mod does this)

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#44]

**Comment by Dain0087** [comment]
I changed the information in the online help for the tablet, This information now reflects OFPS.net, is this what you wanted?

**Comment by SpanishSurfer** [comment]
sure that helps! Actually, wasteland has a pop up that allows users to click right on it, I thought it was a great idea but not a priority right now.
