### ISSUE TITLE
UGV despawn, fix it

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#46]

**Comment by MagnetAss** [comment]
didn't it start happening when we took out the option to buy "crew" with them? As much as a pain in the ass that was, maybe it was neccessary...

**Comment by MarkusNemesis** [comment]
Make sure you check the garbage collector that removes empty vehicles.

Add it in as an exception class if it is what's removing them.

**Comment by SpanishSurfer** [comment]
I checked it and i think it's working...
