### ISSUE TITLE
New Sounds, lets figure this out

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#47]
Live, saw all of the great work you did, the nuke truck is da bomb!  I took back some minor stuff that I don't think will work on the mission (scripted air strikes, mil tower, indestructible h barriers) but everything else has stayed. 

1 thing that needs work, are the sounds. You've done all of the hard work on sounds but we need our own. Can you list out what sounds we have now that we didn't have before? They all need to be replaced with something all players (new/old) will understand as soon as they hear it. For example, base is under attack, we need a voice saying "Base under attack!" maybe with some background noise, etc. I will gladly create those sounds and then implement into the mission. So list what's available and we can knock this out soon.

**Comment by Dain0087** [comment]
Would it be possible to maybe use some of Westwood Red Alert sound clips?

**Comment by Liveandletdie** [comment]
All the sounds i added are vanilla sounds except the nuke sounds, the vanilla sounds are kind of limited on options as you can hear. Adding new sounds is super easy, for new custom sounds we just need to convert any sound file into the .ogg format, then load it in the Rsc/Sounds.hpp file, then simply reference it when needed. All the alert sounds i added are located in two files and are pretty self explanatory as you will see once you open the files, Client/Functions/Client_DisplayMessage.sqf
for most and for town alerts Client/Functions/Client_OnTownCaptured.sqf
 I do think arma does support custom voices as you mentioned but they might sound kinda robotic....i think game would sound best if we created some custom sounds for each event.

I love the red alert/command and conquer sound idea but that might be a copyright issue...although we could create stuff very similar

**Comment by Dain0087** [comment]
Yeah, I tested and added what is love to the prison sound and it will play MP3, but i removed it because of CPA (Copyright) issues just to see if it would take it
