### ISSUE TITLE
No cash for kills and no cash for capping towns

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#49]
I leave it up to you guys to diagnose and fix.  Needs to be done ASAP.

**Comment by Liveandletdie** [comment]
Its a problem associated with the headless client, if you turn him off it should start working again.

**Comment by SpanishSurfer** [comment]
With hc off,  no cash with towns but cash with kills. Turned on  hc, no
cash for either.
