### ISSUE TITLE
Too many carriers

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#56]
Can we reduce the carriers to just 1?  Really far to the north would be best spot.  We have too many now.

**Comment by Liveandletdie** [comment]
any reason y you dont want more? from our tests they do not affect server FPS and are all set to enablesimulation false like the other structures....i think we are the bare min need the west and north ones

**Comment by SpanishSurfer** [comment]
It's just not realistic to have so many.

**Comment by Liveandletdie** [comment]
beyond just adding some new cool stuff to the map, the idea was to add safe landing areas to areas of the map which are lacking in airstrips, hence the west and north carriers. With the introduction of all the new planes we need some safer land/rearm/repair locations. My vote is to keep west/north and remove east one

**Comment by SpanishSurfer** [comment]
How about one WAY north and one WAY south. Right now a player with a Titan
can easily lock and destroy a plane that lands on them. They're visible
from the shore.

**Comment by Liveandletdie** [comment]
i agree with moving further out....south already has aac and selekano strips. West has nothing, it is the most lacking airspace on the map

**Comment by SpanishSurfer** [comment]
No carrier would ever get that close to hostile shore, hence why use north
and south

**Comment by Liveandletdie** [comment]
south of vikos? Why not one far west?

**Comment by SpanishSurfer** [comment]
East/West part of map don't go out very far.
