### ISSUE TITLE
Have we looked at C.U.P?

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#57]
Stop me if you guys don't like what I'm suggesting, I know you've worked hard.  However, here's my observation of the current BECTI EXT.

A lot of guns don't have custom sounds (making them feel like skins and not true new weapons), many custom vehicles are too weak, don't have enough fire power, or can take an absurd # of titan rounds (balance is lacking).  We have a lot of good content but we need to scale back a bit and try and gain some quality. I feel like after the "newness" of BECTI EXT fades we may lose players because of these issues. Have you guys played with CUP gear/units/vehicles?

I'm going to start messing with it tomorrow after work to see if it's any better, but they are releasing a lot of updates with one as recent as 2 days ago...seems to me like this is the custom content we should focus on. 

Please stop me if you've already tried CUP and had negative results.

**Comment by Liveandletdie** [comment]
The main issue i think we had with CUP is the size....its huge!

**Comment by johnsmm** [comment]
we dont want to go over 4gb mark!   we already went from 2GB mark that we set before lol...

**Comment by Liveandletdie** [comment]
Here you are for reference....
CUP Weapons - 1.1GB - requires CBA
CUP Units - 700MB - requires CBA, CUP weapons
CUP Vehicles - 2.4GB - requires CBA, CUP Units, CUP weapons
CUP Terrains Maps - 1.7GB - requires CUP Core
CUP Terrains Core - 6GB
TOTAL PACK: 11.9GB

We also had RHS requests (not on steam)
@RHSAFRF - 2.14GB
@RHSUSAF - 1.96 GB
TOTAL PACK: 4.1GB

Oh yea please checkout our official Extended mod list, this is where we have been coordinating all our mods, feel free to add items you would like to see!
 https://docs.google.com/spreadsheets/d/1kD86419SBbjXn4s5_MqlHF8jbZjfk_FcGZjEp0DIpl4/edit?usp=sharing

**Comment by SpanishSurfer** [comment]
Hmm, but are they polished and balanced? Could be worth it.

**Comment by johnsmm** [comment]
If there is no way to extract the content out of the CUP packs we not going to use them, our total mod pack size limit is 4GB, i dont want to go more than that.

**Comment by SpanishSurfer** [comment]
Of course you can extract, it's a community project

**Comment by johnsmm** [comment]
magnet was saying it was impossible due to some dependency

**Comment by Liveandletdie** [comment]
We can extract almost anything from any modpack it just depends on the amount of work involved, some mods require much more work then others to pull specific mods from. I have already pulled a few mods this way already but not from CUP....USAF is semi easy and RHS is more difficult.....just need to look through the code and test test test
