### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by Liveandletdie** [SpanishSurfer/becti_zerty_OFPS.Altis#59]
While i love the new sounds and smile every-time i hear them, i did get a few complaints (3-4) the other day about the new sounds. Mainly about the moaning aspect, i think you mentioned refining?

**Comment by SpanishSurfer** [comment]
Yeah,  towns being attacked are to long.  Moaning attracts the right crowd
and pushes away kiddos, my opinion.

**Comment by Dain0087** [comment]
Before i left for awhile i was working on a sound pack ill load it up see what you think>

**Comment by SpanishSurfer** [comment]
No thanks on sound.
