### ISSUE TITLE
Commander camera merger

### ISSUE THREAD

**Issue by SpanishSurfer** [SpanishSurfer/becti_zerty_OFPS.Altis#7]
So I copied all of the files from the old mission that allowed the commander to load the construction camera, except for a dialogs.hpp file which is crashing the mission. I'm sure the error lies in the fact that Zerty uses a tablet to display all of the BECTI info. Unfortunately I'm not experienced enough to solve this error and would greatly appreciate some help from the community.

Here's the upload: 4fdd5d982b6e898fc78433ca966d2fcb1df4cdcb

**Comment by SpanishSurfer** [comment]
Ideally, I want the construction camera to load if you're a commander but the normal menu to pop up if you're NOT a commander and are building something via repair truck all from the tablet.

**Comment by SpanishSurfer** [comment]
Zerty, could use your expert eyes.

**Comment by zerty** [comment]
Annoted the commit, please dont assign me at random, good luck with your integration.

**Comment by SpanishSurfer** [comment]
https://github.com/SpanishSurfer/becti_zerty_OFPS.Altis/commit/4fdd5d982b6e898fc78433ca966d2fcb1df4cdcb

**Comment by thecoolestname36** [comment]
Don't worry, I haven't forgotten about this. just trying to find some free time somewhere.

**Comment by thecoolestname36** [comment]
Yeah, I cannot get my dedicated to load the mission. I keep getting 
EPE manager release (0|0|0)
no matter what I run into

**Comment by thecoolestname36** [comment]
Got that cuz github wasnt pulling the init.sqf.... Now I'm greeted with the lovely "You have teamswapped bug"

**Comment by SpanishSurfer** [comment]
No luck diagnosing why the commander camera isn't working?  If you're getting the teamswap bug, disable swapping on the parameters.

**Comment by SpanishSurfer** [comment]
Cool, I reverted the construction cam work I did to get the mission running again. I'll continue to work on it until you have a chance to modify.

**Comment by thecoolestname36** [comment]
Ill try getting it back in tonight.  Yeah i had team swap disabled and everything but fresh mission first join I would be kicked for team swapping.

**Comment by thecoolestname36** [comment]
Teamswap disabled and still getting kicked for teamswapping.

**Comment by SpanishSurfer** [comment]
I've looked over the code and cannot find the problem, care to investigate?

**Comment by thecoolestname36** [comment]
Line 95 in init_client, the following code allows me into the game:

```
    //missionNamespace setVariable ["CTI_PVF_Client_JoinRequestAnswer", {_this spawn CTI_CL_FNC_JoinRequestAnswer}]; //--- Early PVF, do not spoil the game with the others.
    CTI_P_CanJoin = true;
```

Dont know why yet.

**Comment by SpanishSurfer** [comment]
Zerty implemented team stacking preventive measures so that prob has something to do with it.  I tried to delete all of our stuff and use his stuff.

**Comment by Liveandletdie** [comment]
aa8db171c2f802c371844ac102d53d58b110b845

**Comment by SpanishSurfer** [comment]
Military installation? Any bugs so far?
